### ISSUE TITLE
Request for InteGO2 (GO Similarity Data) using in pretrain state of PTGNN

### ISSUE THREAD

**Issue by Jmpax404** [JieZheng-ShanghaiTech/SL_benchmark#4]
Thank you very much for your contributions to reproducing the SL models, particularly the code for PTGNN preprocessing. It has been incredibly helpful.

During the reproduction process, I encountered an issue: the InteGO2 data is no longer available online.  Could you kindly share the following file?

`.../SLBench/Intego2/simout/from_human_sl_simUI_result.txt`

Or just share the mapping file for the ``20,398 gene names to their index`` in pretrain stage of PTGNN.

Thank you again for your support!

**Comment by FEEEENGYM** [comment]
Thank you for reaching out and for your interest in reproducing the SL models!

We have uploaded the script for InteGO2, along with the required files (**InteGO2.zip** and **InteGO2_data.zip**). These files are available in the `data` directory of this repository. Using this script, you can generate the needed file by running the following command:

```bash
python intego2.py -g path/to/go.obo -a path/to/QuickGO_annotations_all.gaf -f path/to/all_goa_symbol.txt -s 9606 -i path/to/input_goa_symbol.txt -p path/to/from_human_sl_simUI_ -m simUI
```
Please ensure to replace path/to/... with the actual paths to the corresponding files.

**Comment by Jmpax404** [comment]
That's amazing! This is the luckiest thing that has happened to me recently!

Thank you so much for sharing these valuable resources. These materials have significantly advanced my progress.
﻿
Once again, thank you for your remarkable contributions to the SL research field and open-source projects, as well as for your generous support.
﻿
Wishing you continued success! 🫡🫡
